config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :users
  resources :users, only:[:index,:show,:edit,:update]
  resources :post_blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_blog.rb
class PostBlog < ApplicationRecord
  belongs_to :user
  attachment :image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_blogs,dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
 
  def about
  end
end

app/controllers/post_blogs_controller.rb
class PostBlogsController < ApplicationController
  def index
    @post_blogs = PostBlog.all
  end

  def show
    @post_blog = PostBlog.find(params[:id])
  end

  def new
    @post_blog = PostBlog.new
  end

  def create
    @post_blog = PostBlog.new(post_blog_params)
    @post_blog.user_id = current_user.id
    @post_blog.save
    redirect_to post_blog_path(@post_blog.id)
  end

  def edit
    @post_blog = PostBlog.find(params[:id])
    if @post_blog.user.id != current_user.id
      redirect_to post_blogs_path
    end
  end

  def update
    @post_blog = PostBlog.find(params[:id])
    @post_blog.update(post_blog_params)
    redirect_to post_blog_path(@post_blog.id)
  end

  def destroy
    blog = PostBlog.find(params[:id])
    blog.destroy
    redirect_to post_blogs_path
  end

  private

  def post_blog_params
    params.require(:post_blog).permit(:title,:body,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_blogs = @user.post_blogs
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end 
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_blogs_helper.rb
module PostBlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Home",user_path(current_user) %>
      </li>
      <li>
        <%= link_to "New Post",new_post_blog_path %>
      </li>
      <li>
        <%= link_to "Blogs",post_blogs_path %>
      </li>
      <li>
        <%= link_to "Users",users_path %>
      </li>
      <li>
        <%= link_to "Logout",destroy_user_session_path,method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home",root_path %>
      </li>
      <li>
        <%= link_to "About",about_path%>
      </li>
      <li>
        <%= link_to "sign up",new_user_registration_path %>
      </li>
      <li>
        <%= link_to "login",new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/post_blogs/edit.html.erb
<h2>Editing Blog</h2>
<%= form_with model:@post_blog,local: true do |f| %>
  <label for="title">Title</label>
  <%= f.text_field :title, id:"title" %>
  <label for="image">Image</label>
  <%= f.attachment_field :image, id:"image" %>
  <label for="text">Text</label>
  <%= f.text_field :body, id:"text" %>
  <%= f.submit 'Edit Blog' %>
<% end %>

<%= link_to 'Show',post_blog_path(@post_blog.id) %> |
<%= link_to 'Back',post_blogs_path %>

app/views/post_blogs/index.html.erb
<h2>Blogs</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @post_blogs.each do |blog| %>
      <tr>
        <td>
          <%= link_to user_path(blog.user.id) do %>
            <%= attachment_image_tag blog.user,:profile_image,format:"jpeg",fallback:"no_image.jpg",size:"40x40" %><br>
            <%= blog.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to post_blog_path(blog.id) do %>
            <%= blog.title %>
          <% end %>
        </td>
        <td><%= blog.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'users/user_info',user:current_user %>

app/views/post_blogs/new.html.erb
<h1>New Blog</h1>
<%= form_with model:@post_blog,local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%=f.submit '投稿' %>
<% end %>

app/views/post_blogs/show.html.erb
<h1>Blog</h1>
<h3><%= @post_blog.title %></h3>
<p><%= @post_blog.created_at.strftime('%Y/%m/%d') %></p>
<%= attachment_image_tag @post_blog, :image,:fill,500,500,format:'jpeg' %>
<p><%= @post_blog.body %></p>
<% if @post_blog.user == current_user %>
  <%= link_to "Edit",edit_post_blog_path(@post_blog.id) %>
  <%= link_to "Destroy",post_blog_path(@post_blog),method: :delete %>
<% end %>

app/views/users/_user_info.html.erb
<h3>User info</h3>
  <%= attachment_image_tag user,:profile_image,fallback:"no_image.jpg",size:'100x100' %>
  <table>
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to 'Edit',edit_user_path(user.id) %>

app/views/users/edit.html.erb
<h2>Editing User</h2>
<%= form_with model:@user,local:true do |f| %>
  <label for="name">Name</label>
  <%= f.text_field :name,id:"name" %>
  <label for="image">Image</label>
  <%= f.attachment_field :profile_image,id:"image" %>
  <label for="introduction">Introduction</label>
  <%= f.text_area :introduction,id:"introduction" %>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user,:profile_image,format:"jpeg",fallback: "no_image.jpg",size:"40x40" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show',user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'users/user_info',user:current_user%>

app/views/users/show.html.erb
<h2><%= @user.name %> Blogs</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Text</td>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @post_blogs.each do |blog| %>
      <tr>
        <td>
          <%= attachment_image_tag blog.user,:profile_image,format:"jpeg",fallback:"no_image.jpg",size:"40x40" %>
        </td>
        <td>
          <%= link_to post_blog_path(blog.id) do %>
            <%= blog.title %>
          <% end %>
        </td>
        <td>
          <%= blog.body.truncate(15) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'users/user_info',user:@user %>